export const buttonMap: { [key: string]: string } = {
  '0': '0.svg',
  '1': '1.svg',
  '2': '2.svg',
  '3': '3.svg',
  '4': '4.svg',
  '1+2': '1+2.svg',
  '1+3': '1+3.svg',
  '1+4': '1+4.svg',
  '2+3': '2+3.svg',
  '2+4': '2+4.svg',
  '3+4': '3+4.svg',
  '1+2+3': '1+2+3.svg',
  '1+2+4': '1+2+4.svg',
  '1+3+4': '1+3+4.svg',
  '2+3+4': '2+3+4.svg',
  '1+2+3+4': '1+2+3+4.svg',
};

export const directionMap: { [key: string]: string } = {
  'b': 'b.svg',
  'B': 'bp.svg',
  '[': 'bracketL.svg',
  ']': 'bracketR.svg',
  'd': 'd.svg',
  'D': 'dp.svg',
  'd/b': 'db.svg',
  'D/B': 'dbp.svg',
  'd/f': 'df.svg',
  'D/F': 'dfp.svg',
  'f': 'f.svg',
  'F': 'fp.svg',
  'n': 'n.svg',
  // '*': 'n.svg',
  'u': 'u.svg',
  'U': 'up.svg',
  'u/b': 'ub.svg',
  'U/B': 'ubp.svg',
  'u/f': 'uf.svg',
  'U/F': 'ufp.svg',
};
